description: TCP R2+1D on Kinetics (Finetuning on UCF/HMDB/SS)

target:
  service: amlk8s
  name: itpseasiav100cl
  vc: resrchvc

environment:
  image: wgting96/mmcv:pytorch1.6-cuda10.1-mmcv1.1

storage:
  data:
    storage_account_name: itpseasiadata
    container_name: t-guwan

code:
  code_upload: True
  local_dir: $CONFIG_DIR/../../

jobs:

  - name: 1026_tcp_r2p1d_k4ft
    sku: G8
    command:
      - pip install tensorboard
      - sudo ln -Ts $$PT_OUTPUT_DIR $$PT_CODE_DIR/output
      - export MKL_THREADING_LAYER=GNU
      - bash tools/dist_train.sh configs/tcp/r2plus1d_18_kinetics/pretraining.py 8 --data_dir /mnt/data/action_datasets/ --resume_from /mnt/data/projects/PyVRL/1024_tcp_r2plus1d_k400/pt-results/pt-1024_tcp_r2plus1d_k400-effcd481_1603523671_eb2bee37/tcp/r2plus1d_18_kinetics/pretraining/epoch_79.pth
      - bash tools/dist_train.sh configs/tcp/r2plus1d_18_kinetics/finetune_ucf101.py 8 --data_dir /mnt/data/action_datasets/ --validate
      - bash tools/dist_train.sh configs/tcp/r2plus1d_18_kinetics/finetune_hmdb51.py 8 --data_dir /mnt/data/action_datasets/ --validate
      - bash tools/dist_train.sh configs/tcp/r2plus1d_18_kinetics/finetune_ssv1.py 8 --data_dir /mnt/data/action_datasets/ --validate
    # aml_mpirun:
    #   process_count_per_node: 1
    #   communicator: "OpenMpi"
    submit_args:
      container_args:
        shm_size: 64g
